name: Execute Unit Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: unit-test
        run: |
          npm ci
          npm run test